
image: "archlinux/base"


before_script:
  - pacman -Syyu --noconfirm
  - pacman -Sy grep --noconfirm
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - pacman -Sy gtk3 gcc git fakeroot base-devel --noconfirm
  - export PATH="$HOME/.cargo/bin:$PATH"

stages:
  # - check
  # - publish
  - deploy
  # - post-run


# clean-code:
#   stage: check
#   script:
#     - rustup component add rustfmt-preview
#     - cargo fmt --all -- --check
#   allow_failure: true

# check:
#   stage: check
#   script:
#     - cargo check

# linux-optimized:
#   stage: deploy
#   script:
#     - cargo build --release
#     - rm -r -f files
#     - mkdir files
#     - cp target/release/noughts-and-crosses files
#   when: on_success
#   artifacts:
#     paths:
#       - files
#     expire_in: 2 weeks

windows-optimized:
  stage: deploy
  script:
    - export EDITOR="nano"
    - echo $EDITOR
    - export VISUAL="nano"
    - rustup target add x86_64-pc-windows-gnu
    - cat /etc/pacman.conf
    - echo [archlinuxfr] >> /etc/pacman.conf
    - echo SigLevel = Never >> /etc/pacman.conf
    - echo Server = http://repo.archlinux.fr/x86_64/$arch >> /etc/pacman.conf
    - echo [multilib] >> /etc/pacman.conf
    - echo Include = /etc/pacman.d/mirrorlist >> /etc/pacman.conf
    - cat /etc/pacman.conf
    - mkdir .cargo
    - touch .cargo/config
    - echo [target.x86_64-pc-windows-gnu] >> .cargo/config
    - echo     linker = \"x86_64-w64-mingw32-gcc\" >> .cargo/config
    - echo     ar = \"x86_64-w64-mingw32-gcc-ar\" >> .cargo/config
    - cat .cargo/config
    - pacman -Syyu --noconfirm
    - pacman -S expac yajl tree meson gtest gmock jq nano --noconfirm
    - pacman -S --needed --noconfirm sudo # Install sudo
    - useradd builduser -m # Create the builduser
    - passwd -d builduser # Delete the buildusers password
    - printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers # Allow the builduser passwordless sudo
    - sudo -u builduser bash -c 'cd ~ && curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pod2man && makepkg PKGBUILD --skippgpcheck && sudo pacman -U pod2man*.tar.xz --noconfirm' 
    - sudo -u builduser bash -c 'cd ~ && curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=cower && makepkg PKGBUILD --skippgpcheck && sudo pacman -U cower*.tar.xz --noconfirm' 
    - sudo -u builduser bash -c 'cd ~ && curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=auracle-git && makepkg PKGBUILD --skippgpcheck && sudo pacman -U auracle-git*.tar.xz --noconfirm'
    - sudo -u builduser bash -c 'cd ~ && curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=pacaur && makepkg PKGBUILD --skippgpcheck && sudo pacman -U pacaur*.tar.xz --noconfirm'
    - pacaur -S --help
    # - sudo -u builduser bash -c 'cd ~ && pacaur -Syyu --noconfirm'
    - sudo -u builduser bash -c 'cd ~ && pacaur -S mingw-w64-gcc mingw-w64-freetype2-bootstrap mingw-w64-cairo-bootstrap --noconfirm'
    - sudo -u builduser bash -c 'cd ~ && pacaur -S mingw-w64-harfbuzz --noconfirm'
    - sudo -u builduser bash -c 'cd ~ && pacaur -S mingw-w64-pango --noconfirm'
    - sudo -u builduser bash -c 'cd ~ && pacaur -S mingw-w64-poppler --noconfirm'
    - sudo -u builduser bash -c 'cd ~ && pacaur -S mingw-w64-gtk3--noconfirm'
    - export PKG_CONFIG_ALLOW_CROSS=1
    - export PKG_CONFIG_PATH=/usr/i686-w64-mingw32/lib/pkgconfig
    - cargo build --target=x86_64-pc-windows-gnu --release
    - rm -r -f files
    - tree
    - mkdir files
    - cp target/release/noughts-and-crosses files
  when: on_success
  artifacts:
    paths:
      - files
    expire_in: 2 weeks

# cratesio:
#   stage: publish
#   script:
#     - rm -r -f files
#     - cargo login $CARGO_LOGIN
#     - cargo package
#     - cargo publish
#   when: on_success
#   only:
#     refs:
#       - stable
#   allow_failure: true


# clippy:
#   stage: post-run
#   script:
#     - rustup default nightly
#     - rustup update
#     - rustup component add clippy-preview
#     - cargo clippy -- -D clippy::pedantic
#   allow_failure: true