
image: "rust:latest"


stages:
  - post-run



clippy:
  stage: post-run
  script:
    - apt-get update
    - apt-get install libgtk-3-dev -y
    - rustup component add clippy-preview
    - cargo clippy
  allow_failure: true