
image: "rust:latest"


stages:
  - check
  - test
  - publish
  - deploy
  - post-run


clean-code:
  stage: check
  script:
    - rustup component add rustfmt-preview
    - cargo fmt --all -- --check
  allow_failure: true

check:
  stage: check
  script:
    - apt-get update
    - apt-get install libgtk-3-dev -y
    - cargo check


unittests:
  stage: test
  script:
    - apt-get update
    - apt-get install libgtk-3-dev -y
    - cargo test --release

benchmarktests:
  stage: test
  script:
    - apt-get update
    - apt-get install libgtk-3-dev -y
    - cargo bench

linux-optimized:
  stage: deploy
  script:
    - apt-get update
    - apt-get install libgtk-3-dev -y
    - cargo build --release
    - rm -r -f files
    - mkdir files
    - cp target/release/noughts-and-crosses files
  when: on_success
  artifacts:
    paths:
      - files
    expire_in: 2 weeks

cratesio:
  stage: publish
  script:
    - apt-get update
    - apt-get install libgtk-3-dev -y
    - rm -r -f files
    - cargo login $CARGO_LOGIN
    - cargo package
    - cargo publish
  when: on_success
  only:
    refs:
      - stable
  allow_failure: true


clippy:
  stage: post-run
  script:
    - apt-get update
    - apt-get install libgtk-3-dev -y
    - rustup default nightly
    - rustup update
    - rustup component add clippy-preview
    - cargo clippy -- -D clippy::pedantic
  allow_failure: true