
image: "fedora:latest"


before_script:
  - yum update -y
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - yum install gtk3-devel glib2-devel -y 
  - yum install tree -y
  - tree -a
  - cat $HOME/.cargo/env
  - export PATH="$HOME/.cargo/bin:$PATH"
  - echo $PATH
  - sh $HOME/.cargo/env
  - rustup target add x86_64-pc-windows-gnu

stages:
  - check
  - test
  - publish
  - deploy
  - post-run


clean-code:
  stage: check
  script:
    - rustup component add rustfmt-preview
    - cargo fmt --all -- --check
  allow_failure: true

check:
  stage: check
  script:
    - cargo check


unittests:
  stage: test
  script:
    - cargo test --release

benchmarktests:
  stage: test
  script:
    - cargo bench

linux-optimized:
  stage: deploy
  script:
    - cargo build --release
    - rm -r -f files
    - mkdir files
    - cp target/release/noughts-and-crosses files
  when: on_success
  artifacts:
    paths:
      - files
    expire_in: 2 weeks

cratesio:
  stage: publish
  script:
    - rm -r -f files
    - cargo login $CARGO_LOGIN
    - cargo package
    - cargo publish
  when: on_success
  only:
    refs:
      - stable
  allow_failure: true


clippy:
  stage: post-run
  script:
    - rustup default nightly
    - rustup update
    - rustup component add clippy-preview
    - cargo clippy -- -D clippy::pedantic
  allow_failure: true